-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/DiscordLinkedRoles/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE discord_linked_roles_account (
  dlra_id SERIAL NOT NULL,
  dlra_user_id INT NOT NULL,
  dlra_discord_user_id VARCHAR(32) NOT NULL,
  dlra_discord_username VARCHAR(255) DEFAULT '' NOT NULL,
  dlra_refresh_token TEXT NOT NULL,
  dlra_scopes VARCHAR(255) DEFAULT '' NOT NULL,
  dlra_connected_at TIMESTAMPTZ NOT NULL,
  dlra_updated_at TIMESTAMPTZ NOT NULL,
  dlra_last_sync_at TIMESTAMPTZ DEFAULT NULL,
  dlra_last_sync_error VARCHAR(512) DEFAULT NULL,
  PRIMARY KEY(dlra_id)
);

CREATE UNIQUE INDEX dlra_user_id ON discord_linked_roles_account (dlra_user_id);

CREATE UNIQUE INDEX dlra_discord_user_id ON discord_linked_roles_account (dlra_discord_user_id);
