-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/DiscordLinkedRoles/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/discord_linked_roles_account (
  dlra_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  dlra_user_id INT UNSIGNED NOT NULL,
  dlra_discord_user_id VARCHAR(32) NOT NULL,
  dlra_discord_username VARCHAR(255) DEFAULT '' NOT NULL,
  dlra_refresh_token BLOB NOT NULL,
  dlra_scopes VARCHAR(255) DEFAULT '' NOT NULL,
  dlra_connected_at BINARY(14) NOT NULL,
  dlra_updated_at BINARY(14) NOT NULL,
  dlra_last_sync_at BINARY(14) DEFAULT NULL,
  dlra_last_sync_error VARCHAR(512) DEFAULT NULL,
  UNIQUE INDEX dlra_user_id (dlra_user_id),
  UNIQUE INDEX dlra_discord_user_id (dlra_discord_user_id),
  PRIMARY KEY(dlra_id)
) /*$wgDBTableOptions*/;
